### ISSUE TITLE
Volume controls don't seem to work

### ISSUE THREAD

**Issue by leanto** [pascalopitz/sonos-controller-for-chrome#1]
On my Sonos system, the app doesn't seem to be able to control the volume reliably. Sometimes clicking the mute button does nothing, sometimes it mutes but won't unmute. The slider doesn't do anything when dragged. (It doesn't even move.) Clicking on either side doesn't do anything either.

I checked the console output for the background page and the app page and there's not much there except some complaint from react like this:
```
ui.js:37899 Warning: Any use of a keyed object should be wrapped in React.addons.createFragment(object) before being passed as a child.
```

One odd thing is that the `<body>` element of the app page seems to have the `react-draggable-dragging` class assigned multiple times:
```html
<body class=" react-draggable-dragging react-draggable-dragging react-draggable-dragging react-draggable-dragging">
```

I have app version 0.11 on a Pixel v1:
> ChromeOS Version 45.0.2454.98 (64-bit)
> Platform 7262.57.0 (Official Build) stable-channel link
> Firmware Google_Link.2695.1.156

My Sonos is running:
> Version: 5.5 (build 29693090)
> Hardware Version: 1.8.3.7-2

**Comment by leanto** [comment]
The additional `react-draggable-dragging` classes are added every time I try to drag the volume control. I just verified that by dragging a few more times and watching the classes get added.

**Comment by pascalopitz** [comment]
Hey, thanks for this very comprehensive bug report. I cannot replicate this in my ubuntu dev setup, looking into ways to test this without buying a chromebook :/

**Comment by leanto** [comment]
I just read about CloudReady (http://www.neverware.com/) which allows you to install ChromiumOS on older laptops. You may be able to get that to work for you. (I don't know if you can install it on an emulator, but I would guess so.)

I'd like to say that I'd be willing to try to do a bit of debugging, but I have no time. :-(

**Comment by pascalopitz** [comment]
Thanks for that, will give it a whirl ... in the meantime, I have updated to react 0.14.0 and bumped the draggable component as well. Can you let me know how that performs for you?

**Comment by leanto** [comment]
OK, the update to version 0.12 makes the volume control work partially.

In my kitchen, I have a pair of Play:1s in a stereo (L + R) configuration. When I use the stereo slider, only the R speaker's volume is increased. Likewise clicking on the mute button only mutes the R speaker.

Also, the warnings above have changed to:
```
ui.js:36126 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `BrowserList`. See https://fb.me/react-warning-keys for more information.warning
@ ui.js:36126 validateExplicitKey
@ ui.js:26604 validateChildKeys
@ ui.js:26666 ReactElementValidator.createElement
@ ui.js:26771 render
@ ui.js:37758 ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext
@ ui.js:23201 ReactCompositeComponentMixin._renderValidatedComponent
@ ui.js:23221 wrapper
@ ui.js:29646 ReactCompositeComponentMixin.mountComponent
@ ui.js:22834 wrapper
@ ui.js:29646 ReactReconciler.mountComponent
@ ui.js:30274 ReactMultiChild.Mixin.mountChildren
@ ui.js:28977 ReactDOMComponent.Mixin._createContentMarkup
@ ui.js:24080 ReactDOMComponent.Mixin.mountComponent
@ ui.js:23970 ReactReconciler.mountComponent
@ ui.js:30274 ReactMultiChild.Mixin.mountChildren
@ ui.js:28977 ReactDOMComponent.Mixin._createContentMarkup
@ ui.js:24080 ReactDOMComponent.Mixin.mountComponent
@ ui.js:23970 ReactReconciler.mountComponent
@ ui.js:30274 ReactMultiChild.Mixin.mountChildren
@ ui.js:28977 ReactDOMComponent.Mixin._createContentMarkup
 @ ui.js:24080ReactDOMComponent.Mixin.mountComponent @ ui.js:23970ReactReconciler.mountComponent @ ui.js:30274ReactCompositeComponentMixin.mountComponent @ ui.js:22839wrapper @ ui.js:29646ReactReconciler.mountComponent @ ui.js:30274ReactCompositeComponentMixin.mountComponent @ ui.js:22839wrapper @ ui.js:29646ReactReconciler.mountComponent @ ui.js:30274mountComponentIntoNode @ ui.js:28154Mixin.perform @ ui.js:32937batchedMountComponentIntoNode @ ui.js:28170Mixin.perform @ ui.js:32937ReactDefaultBatchingStrategy.batchedUpdates @ ui.js:25730batchedUpdates @ ui.js:31007ReactMount._renderNewRootComponent @ ui.js:28364wrapper @ ui.js:29646ReactMount._renderSubtreeIntoContainer @ ui.js:28433ReactMount.render @ ui.js:28453wrapper @ ui.js:29646(anonymous function) @ ui.js:37221(anonymous function) @ ui.js:40078target.(anonymous function) @ extensions::SafeBuiltins:19safeCallbackApply @ extensions::sendRequest:21handleResponse @ extensions::sendRequest:72
ui.js:36126 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ZoneGroupList`. See https://fb.me/react-warning-keys for more information.warning @ ui.js:36126validateExplicitKey @ ui.js:26604validateChildKeys @ ui.js:26666ReactElementValidator.createElement @ ui.js:26771render @ ui.js:39871ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ui.js:23201ReactCompositeComponentMixin._renderValidatedComponent @ ui.js:23221wrapper @ ui.js:29646ReactCompositeComponentMixin._updateRenderedComponent @ ui.js:23174ReactCompositeComponentMixin._performComponentUpdate @ ui.js:23158ReactCompositeComponentMixin.updateComponent @ ui.js:23087wrapper @ ui.js:29646ReactCompositeComponentMixin.performUpdateIfNecessary @ ui.js:23035ReactReconciler.performUpdateIfNecessary @ ui.js:30339runBatchedUpdates @ ui.js:31042Mixin.perform @ ui.js:32937Mixin.perform @ ui.js:32937assign.perform @ ui.js:30999flushBatchedUpdates @ ui.js:31060wrapper @ ui.js:29646Mixin.closeAll @ ui.js:33003Mixin.perform @ ui.js:32950ReactDefaultBatchingStrategy.batchedUpdates @ ui.js:25730enqueueUpdate @ ui.js:31089enqueueUpdate @ ui.js:30677ReactUpdateQueue.enqueueSetState @ ui.js:30843ReactComponent.setState @ ui.js:22409_onChange @ ui.js:39846EventEmitter.emit @ ui.js:100emitChange @ ui.js:44423(anonymous function) @ ui.js:44463_invokeCallback @ ui.js:575dispatch @ ui.js:551(anonymous function) @ ui.js:40432(anonymous function) @ ui.js:41830parseString @ ui.js:42532(anonymous function) @ ui.js:41812xhr.onreadystatechange @ ui.js:42475
ui.js:36126 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `ZoneGroup`. See https://fb.me/react-warning-keys for more information.warning @ ui.js:36126validateExplicitKey @ ui.js:26604validateChildKeys @ ui.js:26666ReactElementValidator.createElement @ ui.js:26771render @ ui.js:39762ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ui.js:23201ReactCompositeComponentMixin._renderValidatedComponent @ ui.js:23221wrapper @ ui.js:29646ReactCompositeComponentMixin.mountComponent @ ui.js:22834wrapper @ ui.js:29646ReactReconciler.mountComponent @ ui.js:30274ReactMultiChild.Mixin._mountChildByNameAtIndex @ ui.js:29210ReactMultiChild.Mixin._updateChildren @ ui.js:29114ReactMultiChild.Mixin.updateChildren @ ui.js:29062ReactDOMComponent.Mixin._updateDOMChildren @ ui.js:24357ReactDOMComponent.Mixin.updateComponent @ ui.js:24189ReactDOMComponent.Mixin.receiveComponent @ ui.js:24134ReactReconciler.receiveComponent @ ui.js:30324ReactCompositeComponentMixin._updateRenderedComponent @ ui.js:23176ReactCompositeComponentMixin._performComponentUpdate @ ui.js:23158ReactCompositeComponentMixin.updateComponent @ ui.js:23087wrapper @ ui.js:29646ReactCompositeComponentMixin.performUpdateIfNecessary @ ui.js:23035ReactReconciler.performUpdateIfNecessary @ ui.js:30339runBatchedUpdates @ ui.js:31042Mixin.perform @ ui.js:32937Mixin.perform @ ui.js:32937assign.perform @ ui.js:30999flushBatchedUpdates @ ui.js:31060wrapper @ ui.js:29646Mixin.closeAll @ ui.js:33003Mixin.perform @ ui.js:32950ReactDefaultBatchingStrategy.batchedUpdates @ ui.js:25730enqueueUpdate @ ui.js:31089enqueueUpdate @ ui.js:30677ReactUpdateQueue.enqueueSetState @ ui.js:30843ReactComponent.setState @ ui.js:22409_onChange @ ui.js:39846EventEmitter.emit @ ui.js:100emitChange @ ui.js:44423(anonymous function) @ ui.js:44463_invokeCallback @ ui.js:575dispatch @ ui.js:551(anonymous function) @ ui.js:40432(anonymous function) @ ui.js:41830parseString @ ui.js:42532(anonymous function) @ ui.js:41812xhr.onreadystatechange @ ui.js:42475
ui.js:36126 Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of `QueueList`. See https://fb.me/react-warning-keys for more information.warning @ ui.js:36126validateExplicitKey @ ui.js:26604validateChildKeys @ ui.js:26666ReactElementValidator.createElement @ ui.js:26771render @ ui.js:38911ReactCompositeComponentMixin._renderValidatedComponentWithoutOwnerOrContext @ ui.js:23201ReactCompositeComponentMixin._renderValidatedComponent @ ui.js:23221wrapper @ ui.js:29646ReactCompositeComponentMixin._updateRenderedComponent @ ui.js:23174ReactCompositeComponentMixin._performComponentUpdate @ ui.js:23158ReactCompositeComponentMixin.updateComponent @ ui.js:23087wrapper @ ui.js:29646ReactCompositeComponentMixin.performUpdateIfNecessary @ ui.js:23035ReactReconciler.performUpdateIfNecessary @ ui.js:30339runBatchedUpdates @ ui.js:31042Mixin.perform @ ui.js:32937Mixin.perform @ ui.js:32937assign.perform @ ui.js:30999flushBatchedUpdates @ ui.js:31060wrapper @ ui.js:29646Mixin.closeAll @ ui.js:33003Mixin.perform @ ui.js:32950ReactDefaultBatchingStrategy.batchedUpdates @ ui.js:25730enqueueUpdate @ ui.js:31089enqueueUpdate @ ui.js:30677ReactUpdateQueue.enqueueSetState @ ui.js:30843ReactComponent.setState @ ui.js:22409_onChange @ ui.js:38800EventEmitter.emit @ ui.js:75emitChange @ ui.js:44137(anonymous function) @ ui.js:44235_invokeCallback @ ui.js:575dispatch @ ui.js:551(anonymous function) @ ui.js:40485(anonymous function) @ ui.js:41084parseString @ ui.js:42532(anonymous function) @ ui.js:41050(anonymous function) @ ui.js:43379parseString @ ui.js:42532(anonymous function) @ ui.js:43362xhr.onreadystatechange @ ui.js:42475
```

**Comment by pascalopitz** [comment]
Thanks, will have a look when I get a spare moment.

**Comment by pascalopitz** [comment]
hey, I can totally not replicate this. Could you send me your topology info.:

http://{sonos player ip}:1400/status/topology

**Comment by leanto** [comment]
## Zone Players

Zone Name|	Coordinator|	Group|	Location|	UUID|	Version|	MinCompatVer|	Compat|	WiMode|	HasSSID|	WiFreq|	WiEna|	BeEx
---|---|---|---|---|---|---|---|---|---|---|---|---
Kitchen|	false|	RINCON_B8E937B79BEA01400:1|	http://192.168.1.42:1400/xml/device_description.xml|	RINCON_B8E937B797EC01400|	29.6-93090|	28.0-00000|		1|	1|	2412|	1|	0
Kitchen|	true|	RINCON_B8E937B79BEA01400:1|	http://192.168.1.20:1400/xml/device_description.xml|	RINCON_B8E937B79BEA01400|	29.6-93090|	28.0-00000|		1|	1|	2412|	1|	0

Hope that helps.

**Comment by leanto** [comment]
BTW, I verified that this is still happening and that it wasn't a one-off. However I did have to start the app twice because the first time the volume didn't respond at all.

**Comment by leanto** [comment]
I just added some debug info while the app was running in Chrome. In particular, I had it print the URL that the sonos.request() method is using. Turns out, it's using:
```
http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
```
when updating the volume but
```
http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
```
when querying state. This seems very odd. I'll try to get stack traces for these.

**Comment by leanto** [comment]
Here's one while updating the position:
```
uri = http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
action = "urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo" Error: for stack trace
    at Sonos.request (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:40986:93)
    at Sonos.currentTrack (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:41173:16)
    at chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:40508:10
    at chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:41890:12
    at chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:41004:13
    at Object.parseString (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:42533:5)
    at chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:40999:45
    at XMLHttpRequest.xhr.onreadystatechange (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:42476:5)
```
Here's one while setting the volume:
```
uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace
    at Sonos.request (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:40986:93)
    at Sonos.setVolume (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:41760:9)
    at Object.setPlayerVolume (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:37116:9)
    at chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:39367:46
    at Array.forEach (native)
    at VolumeControls._changeGroupVolume (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:39348:9)
    at chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:39637:17
    at debounced (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:8541:27)
    at VolumeSlider._onDrag (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:39639:4)
    at module.exports.React.createClass.handleDrag (chrome-extension://cojfokmeikpnickdpoopoockilamcmoc/js/ui.js:17040:16)
```
and even though I see in the stack trace that there is a `forEach`, I only see `192.168.1.42` being updated. Here's a log with the stack traces collapsed:
```
uri = http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
action = "urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
action = "urn:schemas-upnp-org:service:AVTransport:1#GetTransportInfo" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
action = "urn:schemas-upnp-org:service:AVTransport:1#GetTransportInfo" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
action = "urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.42:1400/MediaRenderer/RenderingControl/Control
action = "urn:schemas-upnp-org:service:RenderingControl:1#SetVolume" Error: for stack trace(…)
ui.js:40986 uri = http://192.168.1.20:1400/MediaRenderer/AVTransport/Control
action = "urn:schemas-upnp-org:service:AVTransport:1#GetPositionInfo" Error: for stack trace(…)
```

**Comment by leanto** [comment]
Oh, this is interesting. I put a debug statement in `_changeGroupVolume` to dump the state and this is what is there:
```
_dragEndTimer: 435
_hideTimer: 436
_reactInternalInstance: ReactCompositeComponentWrapper
context: Object
getDOMNode: (...)
isMounted: (...)
props: Object
refs: Object
replaceProps: (...)
replaceState: (...)
setProps: (...)
state: Object
  dragging: false
  isExpanded: false
  players: Object
    192.168.1.42: Object
      muted: false
      name: "Kitchen (L + R)"
      volume: 17
      __proto__: Object
    __proto__: Object
  __proto__: Object
updater: Object
__proto__: VolumeControls
```
Note that there is only one entry in the `state.players` object.

**Comment by pascalopitz** [comment]
Indeed ... which is not the coordinator ...

**Comment by pascalopitz** [comment]
Maybe have a look at https://github.com/pascalopitz/sonos-controller-for-chrome/blob/master/src/ui/stores/VolumeControlStore.js#L35 and see what's coming through there.

If things are already out of whack there, this is the place to look:

https://github.com/pascalopitz/sonos-controller-for-chrome/blob/master/src/ui/services/SonosService.js#L471

**Comment by leanto** [comment]
It's inconsistent at `VolumeControlStore`. Sometimes it has the right one (and then the volume works as expected) and sometimes it doesn't. Here's an example where it doesn't:
```js
behindwifiext: "0"
bootseq: "17"
channelfreq: "2412"
coordinator: "false"
group: "RINCON_B8E937B79BEA01400:1"
hasconfiguredssid: "1"
host: "192.168.1.42"
legacycompatibleversion: "24.0-0000"
location: "http://192.168.1.42:1400/xml/device_description.xml"
mincompatibleversion: "28.0-00000"
name: "Kitchen (L + R)"
uuid: "RINCON_B8E937B797EC01400"
version: "29.6-93090"
wifienabled: "1"
wirelessmode: "1"
```
Looking at `SonosService.excludeStereoPairs`:
```js
	excludeStereoPairs: function excludeStereoPairs(zones) {

		// TODO: find a better place for this
		zones.forEach(function (z) {
			var matches = REG.exec(z.location);
			z.host = matches[1];
		});

		return (0, _lodash2['default'])(zones).groupBy('name').map(function (g) {
			// TODO: what happens when a sub is added?
			if (g.length === 2) {
				g[0].name = g[0].name + ' (L + R)';
			}
			return _lodash2['default'].findWhere(g, 'coordinator', 'true') || g[0]; // <== PROBLEM
		}).value();
		return zones;
	}
```
The problem line, as pointed to above is:
```
_lodash2['default'].findWhere(g, 'coordinator', 'true') || g[0]
```
because it turns out that `findWhere` always returns `undefined`, so `g[0]` is taken.

From the console, this gives the correct results:
```js
_lodash2['default'].findWhere(g, {'coordinator': 'true'})
```

**Comment by pascalopitz** [comment]
Makes me think that the lookup {'coordinator': 'true'} might be sometimes not a string, or captialized or something. Can you just dump out whatever comes through as zones?

**Comment by leanto** [comment]
It's just that the call is wrong--you forgot to wrap the `'coordinator', 'true'` in curly braces.

**Comment by pascalopitz** [comment]
Doh! Yes, you're right. Fixed and pushed to chrome store etc ...

**Comment by leanto** [comment]
Just got the update to version 0.14. Thanks for the shout-out in the contributors section. :-)

So far, it seems to work great. I'm going to close this and I'll file a new bug if something else comes up.

**Comment by pascalopitz** [comment]
Thanks for helping out!
